server:
  port: 8662

spring:
  application:
    name: gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    cpu-load-service:
      path: /cpuload/**
      serviceId: cpu-load-service
      stripPrefix: true
    call-service:
      path: /callservice/**
      serviceId: call-service
      sripPrefix: true
    db-service:
      path: /dbservice/**
      serviceId: db-service
      stripPrefix: true


management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"