server:
  port: 8010
spring:
  application:
    name: call-service

service:
  url: http://localhost:8020/callme

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"