server:
  port: 8020

spring:
  application:
    name: cpu-load-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"