server:
  port: 8030
spring:
  application:
    name: db-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"