global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['call-service:8010', 'cpu-load:8020', 'db-service:8030', 'eureka-server:8661', 'api-gateway:8662']